version: '3.8'
services:
  db:
    container_name: db_c
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  api:
    depends_on:
      - db
    build:
      context: ./
      target: dev #Change to prod for production
      dockerfile: Dockerfile
    container_name: api_c
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./.env.dev
          action: rebuild
        - path: ./
          target: ./api
          ignore:
            - .git
          action: sync
