name: Publish Backend Docker Image
run-name: Publishing Backend Docker Image...
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - prisma/*
      - src/*
      - .dockerignore
      - Dockerfile
      - package-lock.json
      - package.json
      - server.ts
      - tsconfig.json

jobs:
  push_to_registry_if_merged:
    if: ${{ github.event.pull_request.merged }}
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Backend
        id: backend_meta
        uses: docker/metadata-action@v5
        with:
          images: evandvance/bekindlytodaybackend

      - name: Build and push Backend Docker Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: prod
          tags: evandvance/bekindlytodaybackend:latest
          labels: ${{ steps.backend_meta.outputs.labels }}

      - name: Build and push Backend Docker Dev Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: dev
          tags: evandvance/bekindlytodaybackend:dev
          labels: ${{ steps.backend_meta.outputs.labels }}

  redeploy_render:
    name: Redeploy New Image
    runs-on: ubuntu:latest

    steps:
      - name: Curl Redeply URL
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
