name: Publish Database Docker Image
run-name: Publishing Database Docker Image...
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - prisma/*
      - db/dev/*
      - db/challenges_upsert.sql

jobs:
  push_to_registry_if_merged:
    if: ${{ github.event.pull_request.merged }}
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Database Image
        id: database_meta
        uses: docker/metadata-action@v5
        with:
          images: evandvance/bekindlytodaydatabase

      - name: Build and push Database Production Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: evandvance/bekindlytodaydatabase:latest
          labels: ${{ steps.database_meta.outputs.labels }}

  upsert_production_challenges:
    if: ${{ github.event.pull_request.merged }}
    name: Upsert Production Challenges
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: Install Postgres CLI
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

      - name: Run Upsert
        run: psql --dbname=${{ secrets.PRODUCTION_DATABASE_URL }} -f ./db/challenges_upsert.sql
