name: Redo Seeding Sql

on:
  push:
    paths:
      - prisma/migrations/*

jobs:
  #   get_challenges:
  #     runs-on: ubuntu-latest

  #     steps:
  #       - uses: actions/checkout@v4

  #       - name: Set Up Python
  #         uses: actions/setup-python@v5
  #         with:
  #           python-version: '3.12'

  #       - name: Install Dependecies
  #         run: |
  #           python -m pip install --upgrade pip
  #           python -m pip install pandas

  #       - name: Load Challenge Spreadsheet to SQL
  #         run: python3 ./db/get_challenges_from_spreadsheet.py

  redo_sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Seed Sql
        uses: addnab/docker-run-action@v3
        with:
          image: postgres:16-alpine
          options: -e POSTGRES_PASSWORD=MyDatabasePassword1 -p 5432:5423
          run: |
            npm run redo-sql

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Redid SQL[bpt]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
